### ISSUE TITLE
How to implement your breadcrumbs in lazy loading?

### ISSUE THREAD

**Issue by suriyaJaay** [mutableideas/ngserve-nx-gcp-starter#35]
Hi,

Could you pls tell me, will your breadcrumb help for my below scenario ?

https://stackoverflow.com/questions/71553479/what-is-wrong-with-my-breadcrumbs-angular-11 

Thanks

**Comment by mutableideas** [comment]
Hey Suriya, While I don’t know much about the package in your Stackover Flow Question, I would have to assume they’ve implemented similar in the manner I have.  Meaning, the routes with breadcrumbs follow a parent -> child relationship.  My guess for your issue that in the customer.routing.module.ts the Completed Users List needs to be a child route of the User Dashboard.  That’s how I’ve set it up for my package. Example:

``` typescript 
const routes = {  {    path: ‘dashboard’,   component: DashboardComponent,   data: { breadcrumb: { … breadcrumb properties } },   children: [     { path: ‘user-completed-list’, component: UserCompletedListComponent, data: { breadcrumb: { …breadcrumb properties } } }   ]  }
```

**Comment by mutableideas** [comment]
In response to the title question, the breadcrumb I created does allow for lazy loaded routes.  If you need further details, please see: https://ngserve.io/angular-tutorial-creating-a-navigation-module-for-breadcrumb/
